[logging]
level = "debug"
error_separate = false

[library]
class = "Phydll"
model_file = "./train_models/model_a/perfect_cuda.pt"
backend = "TORCH"
device = "GPU"
batch_size = 500000
transport_layout = "uniform_chunks"

[normalization]
class = "MinMax"
input_min = 0.0
input_max = 1.0
output_min = 0.0
output_max = 1.0

[behavior]
class = "Default"

[application]
class = "MLCouplingApplicationTerrainSolver"
