[logging]
level = "debug"
error_separate = false

[library]
class = "Phydll"
model_file = "./train_models/model_a/perfect_cuda.pt"
backend = "TORCH"
device = "GPU"
batch_size = 500000

[behavior]
class = "Default"

[application]
class = "MLCouplingApplicationTerrainSolver"
model_io_layout = "split_3x3"
