[logging]
level = "debug"
error_separate = false

[library]
class = "AIX"
model_file = "./train_models/model_a/perfect_cuda.pt"

[behavior]
class = "Default"

[application]
class = "MLCouplingApplicationTerrainSolver"
model_io_layout = "flat_contiguous"
